version: 2
jobs:
  build:
    docker:
      - image: nuonic/node-python-awscli
    steps:
      - checkout
      - run:
          command: pip install -r requirement.txt
      - run:
          command: coverage run manage.py test
      - run:
          command: npm install

    {
      "scripts": {
        "start": "my-server -p 3030",
        "cy:run": "cypress run",
        "test": "start-server-and-test start http://localhost:3030 cy:run"
      }
    }
      


