version: 2
jobs:
  build:
    docker:
      - image: booleanbetrayal/circleci-trusty-ruby-node-python-awscli-psql-chrome
    steps:
      - checkout
      - run:
          command: sudo pip install -r requirement.txt
      - run:
          command: coverage run manage.py test
      


