version: 2
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs

    steps:
      - checkout
      - run:
          command: pip install -r requirement.txt
      - run:
          command: coverage run manage.py test



