version: 2
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs

    steps:
      - checkout
      - run:
          command: pip install -r requirement.txt
      - run:
          command: coverage run manage.py test
      - run:
          command: npm install
      - run:
          command: python manage.py makemigrations && python manage.py migrate
      - run:
          command: python manage.py runserver 8000
          background: true
      - run:
          command: apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      - run:
          command: node_modules/.bin/cypress open






