version: 2
jobs:
  build:
    docker:
      - image: frolvlad/alpine-python3



    steps:
      - checkout
      - run:
          command: pip install -r requirement.txt
      - run:
          command: coverage run manage.py test



