version: 2
jobs:
  build:
    docker:
      - image: lilfolr/nodejs-python
    steps:
      - checkout
      - run:
          command: sudo pip install -r requirement.txt
      - run:
          command: coverage run manage.py test
      


