# Generated by Django 2.2 on 2019-04-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appoint_depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='appoint_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer_num', models.CharField(max_length=200)),
                ('emer_descrip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='footer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_description', models.TextField()),
                ('foot_address', models.CharField(max_length=100)),
                ('foot_phone', models.CharField(max_length=20)),
                ('foot_email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='images/')),
                ('slider_u_title', models.CharField(max_length=200)),
                ('slider_l_title', models.CharField(max_length=200)),
                ('slider_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='news_subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_email', models.EmailField(max_length=120)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='opening_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_open', models.CharField(max_length=200)),
                ('time_open', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='our_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=200)),
                ('dep_description', models.TextField()),
                ('dep_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='patient_testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_description', models.TextField()),
                ('pat_image', models.ImageField(upload_to='images/')),
                ('pat_name', models.CharField(max_length=200)),
                ('pat_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='the_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_image', models.ImageField(upload_to='images/')),
                ('new_title', models.CharField(max_length=200)),
                ('new_date', models.CharField(max_length=200)),
                ('new_by_name', models.CharField(max_length=200)),
                ('new_description', models.TextField()),
                ('new_no_comments', models.CharField(max_length=200)),
            ],
        ),
    ]
