# Generated by Django 2.2 on 2019-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faqproqlt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
