# Generated by Django 2.2 on 2019-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_servicebackimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopQualityService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
