# Generated by Django 2.2 on 2019-04-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_servicestabs_main_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesTabs',
        ),
    ]
