# Generated by Django 2.2 on 2019-04-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_servicestabs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesTabs',
        ),
    ]
