# Generated by Django 2.2 on 2019-04-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_servicestabs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='footer_data',
        ),
    ]
