# Generated by Django 2.2 on 2019-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_newbacksimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
    ]
