# Generated by Django 2.2 on 2019-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_latestpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
