# Generated by Django 2.2 on 2019-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_iconboxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patient_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
