# Generated by Django 2.2 on 2019-04-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190419_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
