# Generated by Django 2.2 on 2019-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190419_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadFoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('copy_rights', models.CharField(max_length=200)),
            ],
        ),
    ]
