# Generated by Django 2.2 on 2019-04-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_headfoot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headfoot',
            name='copy_rights',
        ),
    ]
