describe('index', function () {
    it('index', function () {
        cy.visit('http://127.0.0.1:8000/').then(() => {

        });
        cy.get('.current-menu-item > a').contains('Home');
        cy.get('.flex-column > :nth-child(2) > a').contains('About us');
        cy.get('.site-navigation > .flex-column > :nth-child(3) > a').contains('Services');
        cy.get('.flex-column > :nth-child(4) > a').contains('News');
        cy.get('.flex-column > :nth-child(5) > a').contains('Contact');
        cy.get('.flex-column > .call-btn > .d-flex').contains('+34 586 778 8892');
        cy.get('[style="background-image: url(\'/media/images/hero.jpg\')"] > .hero-content-overlay > .container > .row > .col-12 > .entry-header > h1').contains('The Best Medical Services');
        cy.get('[style="background-image: url(\'/media/images/hero.jpg\')"] > .hero-content-overlay > .container > .row > .col-12 > .entry-content > p').contains('Lorem ipsum dolor sit amet, cons ectetur');
        cy.get('[style="background-image: url(\'/media/images/hero.jpg\')"] > .hero-content-overlay > .container > .row > .col-12 > .entry-footer > .button').contains('Read More');
        cy.get('.opening-hours').contains('Opening');
        cy.get('.opening-hours').contains('Monday - Thursday');
        cy.get('.opening-hours').contains('Friday');
        cy.get('.opening-hours').contains('Saturday');
        cy.get('.opening-hours').contains('Sunday');
        cy.get('.emergency-box').contains('Emergency');
        cy.get('.emergency-box').contains('+34 586 778 8892');
        cy.get('.emergency-box').contains('Lorem ipsum dolor sit amet, cons ectetur adipiscing elit.');
        cy.get('.our-departments-wrap > h2').contains('Our');
        cy.get(':nth-child(1) > .our-departments-cont > .entry-header > h3').contains('Cardio');
        cy.get(':nth-child(1) > .our-departments-cont > .entry-content > p').contains('Lorem ipsum dolor sit amet');
        cy.get(':nth-child(1) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(2) > .our-departments-cont > .entry-header > h3').contains('Gastro');
        cy.get(':nth-child(2) > .our-departments-cont > .entry-content > p').contains('Donec malesuada lorem');
        cy.get(':nth-child(2) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(3) > .our-departments-cont > .entry-header > h3').contains('Medical');
        cy.get(':nth-child(3) > .our-departments-cont > .entry-content > p').contains('Lorem maximus mauri');
        cy.get(':nth-child(3) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(4) > .our-departments-cont > .entry-header > h3').contains('Dental');
        cy.get(':nth-child(4) > .our-departments-cont > .entry-content > p').contains('Donec malesuada lorem');
        cy.get(':nth-child(4) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(5) > .our-departments-cont > .entry-header > h3').contains('Surgery');
        cy.get(':nth-child(5) > .our-departments-cont > .entry-content > p').contains('maximus mauris scelerisque');
        cy.get(':nth-child(5) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(6) > .our-departments-cont > .entry-header > h3').contains('Neurology');
        cy.get(':nth-child(6) > .our-departments-cont > .entry-content > p').contains('Donec malesuada lorem');
        cy.get(':nth-child(6) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(7) > .our-departments-cont > .entry-header > h3').contains('Orthopaedy');
        cy.get(':nth-child(7) > .our-departments-cont > .entry-content > p').contains('Lorem maximus mauris');
        cy.get(':nth-child(7) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(8) > .our-departments-cont > .entry-header > h3').contains('Pediatry');
        cy.get(':nth-child(8) > .our-departments-cont > .entry-content > p').contains('Donec malesuada lorem');
        cy.get(':nth-child(8) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get(':nth-child(9) > .our-departments-cont > .entry-header > h3').contains('Ophthal');
        cy.get(':nth-child(9) > .our-departments-cont > .entry-content > p').contains('Lorem maximus mauris');
        cy.get(':nth-child(9) > .our-departments-cont > .entry-footer > a').contains('read');
        cy.get('.testimonial-section > :nth-child(1) > .row > .col-12 > h2').contains('Patient');
        cy.get('.testimonial-user').contains('Nina Dobrev');
        cy.get('.testimonial-user').contains('University');
        cy.get('.the-news > .container > :nth-child(1) > :nth-child(1) > h2').contains("The News");
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > h3').contains('The');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-date > label').contains('Date');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-date > a').contains('April');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-by > label').contains('By');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-by > a').contains('Dr');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .post-comments > a').contains('comments');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-content > p').contains('Lorem ipsum dolor sit ame');
        cy.get(':nth-child(2) > .the-news-wrap > .entry-header > h3').contains('All');
        cy.get(':nth-child(2) > .the-news-wrap > .entry-header > .post-metas > .posted-date > label').contains('Date');
        cy.get(':nth-child(2) > .the-news-wrap > .entry-header > .post-metas > .posted-date > a').contains('April');
        cy.get(':nth-child(2) > .the-news-wrap > .entry-header > .post-metas > .posted-by > label').contains('By');
        cy.get(':nth-child(2) > .the-news-wrap > .entry-header > .post-metas > .posted-by > a').contains('Dr');
        cy.get(':nth-child(2) > .the-news-wrap > .entry-header > .post-metas > .post-comments > a').contains('comments');
        cy.get(':nth-child(2) > .the-news-wrap > .entry-content > p').contains('Lorem ipsum dolor sit ame');
        cy.get('.subscribe-banner > .container > .row > .col-12 > h2').contains('newsletter');
        cy.get('#user_subscription > #submit').contains('Subscribe');
        cy.get('.foot-about > :nth-child(2)').contains('Lorem ipsum dolor');
        cy.get('.copyright').contains('Copyright');
        cy.get('.foot-contact > h2').contains('Contact');
        cy.get('.foot-contact > .p-0 > :nth-child(1)').contains('Addtress');
        cy.get('.foot-contact > .p-0 > :nth-child(1)').contains('Mitlton');
        cy.get('.foot-contact > .p-0 > :nth-child(2)').contains('Phone');
        cy.get('.foot-contact > .p-0 > :nth-child(2)').contains('+53 345 7953 32453');
        cy.get('.foot-contact > .p-0 > :nth-child(3)').contains('Email');
        cy.get('.foot-contact > .p-0 > :nth-child(3)').contains('yourmail@gmail.com');
        cy.get('.foot-links > h2').contains('Useful');
        cy.get('.p-0 > :nth-child(1) > a').contains('Home');
        cy.get('.p-0 > :nth-child(2) > a').contains('About');
        cy.get('.p-0 > :nth-child(3) > a').contains('Departments');
        cy.get('.p-0 > :nth-child(4) > a').contains('Contact');
        cy.get('.p-0 > :nth-child(5) > a').contains('FAQ');
        cy.get('.p-0 > :nth-child(6) > a').contains('Testimonials')

    })
});
