describe('news', function () {
    it('news', function () {
        cy.visit('http://127.0.0.1:8000/news').then(() => {

        });
        cy.get('.current-menu-item > a').contains('Home');
        cy.get('.flex-column > :nth-child(2) > a').contains('About us');
        cy.get('.site-navigation > .flex-column > :nth-child(3) > a').contains('Services');
        cy.get('.flex-column > :nth-child(4) > a').contains('News');
        cy.get('.flex-column > :nth-child(5) > a').contains('Contact');
        cy.get('.flex-column > .call-btn > .d-flex').contains('+34 586 778 8892');
        cy.get('h1').contains('News');
        cy.get('.breadcrumbs > .d-flex > :nth-child(1) > a').contains('Home');
        cy.get('.breadcrumbs > .d-flex > :nth-child(2)').contains('News');
        cy.get('.breadcrumbs > .d-flex > :nth-child(1) > a').contains('Home');
        cy.get('.flex-wrap > .flex').contains('Search');
        cy.get('.sidebar-cats > .widget-title').contains('Categories');
        // cy.get('.sidebar-cats > :nth-child(2) > li > a').contains('Radiology');
        cy.get('.sidebar-cats > :nth-child(3) > li').contains('Cardiology');
        cy.get('.sidebar-cats > :nth-child(4) > li').contains('Gastroenterology');
        cy.get('.sidebar-cats > :nth-child(5) > li').contains('Neurology');
        cy.get('.sidebar-cats > :nth-child(6) > li').contains('General surgery');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > h3').contains('The latest');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-date > label').contains('Date');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-date > a').contains('April');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-by > label').contains('By');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .posted-by > a').contains('Dr');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-header > .post-metas > .post-comments > a').contains('Comments');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-content > p').contains('Lorem ipsum');
        cy.get(':nth-child(1) > .the-news-wrap > .entry-footer > .button').contains('Read');
        cy.get(':nth-child(2) > .pagination > .active > a').contains('01');
        cy.get(':nth-child(2) > .pagination > :nth-child(2) > a').contains('02');
        cy.get(':nth-child(2) > .pagination > :nth-child(3) > a').contains('03');
        cy.get('.popular-posts > .widget-title').contains('Latest');
        cy.get(':nth-child(1) > .entry-content > .entry-title > a').contains('A big');
        cy.get(':nth-child(1) > .entry-content > .posted-date').contains('Feb');
        cy.get(':nth-child(2) > .entry-content > .entry-title > a').contains('Dentistry');
        cy.get(':nth-child(2) > .entry-content > .posted-date').contains('Feb');
        cy.get(':nth-child(3) > .entry-content > .entry-title > a').contains('When');
        cy.get(':nth-child(3) > .entry-content > .posted-date').contains('2018');
        cy.get('.opening-hours > .d-flex').contains('Opening');
        cy.get('.opening-hours > :nth-child(2) > li').contains('Monday');
        cy.get('.opening-hours > :nth-child(3) > li').contains('Friday');
        cy.get('.opening-hours > :nth-child(4) > li').contains('Saturday');
        cy.get('.opening-hours > :nth-child(5) > li').contains('Sunday');
        cy.get('.emergency-box > h2.d-flex').contains('Emergency');
        cy.get('.emergency-box > .call-btn > .d-flex').contains('+');
        cy.get('.emergency-box > p').contains('Lorem ipsum');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-header > h3').contains('All');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-header > .post-metas > .posted-date > label').contains('Date');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-header > .post-metas > .posted-date > a').contains('April');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-header > .post-metas > .posted-by > label').contains('By');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-header > .post-metas > .posted-by > a').contains('Dr');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-header > .post-metas > .post-comments > a').contains('Comments');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-content > p').contains('Lorem ipsum');
        cy.get(':nth-child(3) > .the-news-wrap > .entry-footer > .button').contains('Read');
        cy.get(':nth-child(4) > .pagination > .active > a').contains('01');
        cy.get(':nth-child(4) > .pagination > :nth-child(2) > a').contains('02');
        cy.get(':nth-child(4) > .pagination > :nth-child(3) > a').contains('03');
        cy.get('.subscribe-banner > .container > .row > .col-12 > h2').contains('newsletter');
        cy.get('#user_subscription > .button').contains('Subscribe');
        cy.get('#email').type('medart402@gmail.com');
        cy.get('#submit').click();
        cy.get('.foot-about > :nth-child(2)').contains('Lorem ipsum dolor');
        cy.get('.copyright').contains('Copyright');
        cy.get('.foot-contact > h2').contains('Contact');
        cy.get('.foot-contact > .p-0 > :nth-child(1)').contains('Addtress');
        cy.get('.foot-contact > .p-0 > :nth-child(1)').contains('Mitlton');
        cy.get('.foot-contact > .p-0 > :nth-child(2)').contains('Phone');
        cy.get('.foot-contact > .p-0 > :nth-child(2)').contains('+53 345 7953 32453');
        cy.get('.foot-contact > .p-0 > :nth-child(3)').contains('Email');
        cy.get('.foot-contact > .p-0 > :nth-child(3)').contains('yourmail@gmail.com');
        cy.get('.foot-links > h2').contains('Useful');
        cy.get('.p-0 > :nth-child(1) > a').contains('Home');
        cy.get('.p-0 > :nth-child(2) > a').contains('About');
        cy.get('.p-0 > :nth-child(3) > a').contains('Departments');
        cy.get('.p-0 > :nth-child(4) > a').contains('Contact');
        cy.get('.p-0 > :nth-child(5) > a').contains('FAQ');
        cy.get('.p-0 > :nth-child(6) > a').contains('Testimonials')

    })
});
